greenhouses:
  - greenhouse1
  - greenhouse2
  - greenhouse3

sensors:
  temperature:
    base: 22.5
    fluctuation: 4.5
    ids: ["001", "002"]
  humidity:
    base: 50.0
    fluctuation: 10.0
    ids: ["001"]
  water_ph:
    base: 6.0
    fluctuation: 0.5
    ids: ["001", "002"]
  ec:
    base: 2.0
    fluctuation: 0.5
    ids: ["001", "002"]
  water_temperature:
    base: 21.0
    fluctuation: 3.0
    ids: ["001", "002"]
  light:
    base: 900
    fluctuation: 300
    ids: ["001", "002"]
